#!/bin/bash

if [ -n "${PERCONA_DEBUG}" ]; then
  set -x
  export DEBCONF_DEBUG=developer
fi

set -e

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi

stop_server() {
  set +e
  if [ -x /usr/sbin/invoke-rc.d ]; then
    invoke-rc.d proxysql restart
  else
    /etc/init.d/proxysql restart
  fi
}

case "$1" in
    
  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    stop_server
  ;;

  *)
    echo "postrm called with unknown argument '$1'" 1>&2
    exit 1
  ;;

esac

if [ "$1" = "purge" ]; then
  db_input high proxysql/postrm_remove_data || true
  db_go || true
  db_get proxysql/postrm_remove_data || true
  if [ "$RET" = "true" ]; then
    rm -rf /var/lib/proxysql
    rm -rf /var/run/proxysql
    userdel proxysql || true
  fi
  db_fset proxysql/postrm_remove_data seen false
fi

#DEBHELPER#

exit 0
